spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///boot?characterEncoding=utf-8&serverTimezone=PRC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
